---
title: '20200325'
author: "陳冠龍"
date: "3/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)

majors10_factor <- factor(majors10_char)
# 或
majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)

typeof(majors10_factor)
class(majors10_factor)
```

```{r}
as.integer(majors10_factor) 
levels(majors10_factor)
```

```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算
stringInteger+2
```

```{r}
trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
typeof(trueInteger)
trueInteger+2
```

```{r}
studentId <- c(410773002, 410773015)
studentId <- as.character(studentId)
class(studentId)
```

```{r}
library(lubridate)
```

```{r}
tpeTime <- ymd_hms("2020-03-18 13:52:40",
        tz="Asia/Taipei")
typeof(tpeTime)
as.double(tpeTime)
```

```{r}
pgTime <- mdy_hms("Mar.18, 2020, 05:52:40",
                  tz="Europe/Lisbon")
typeof(pgTime)
as.double(pgTime)
```

```{r}
with_tz(tpeTime, tzone="UTC")
with_tz(pgTime, tzone="UTC")
```

```{r}
studentTime <- c(ymd_hms('2020-03-04T08:15:28Z'),
                 ymd_hms('2020-03-11 16:11:43',tz="Asia/Taipei"),
                 ymd_hms('2020-03-11 16:11:43',tz="Asia/Taipei"))
studentTime
```

